<?php
require_once '../auth_check.php'; // Inclure la vérification de session
require_once '../config.php';
require_once '../tcpdf/tcpdf.php'; // Inclure le fichier TCPDF

// Créer une nouvelle instance TCPDF
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Paramètres du document PDF
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Your Name');
$pdf->SetTitle('Students List');
$pdf->SetSubject('List of Students');
$pdf->SetKeywords('TCPDF, PDF, students, list');

// En-tête et pied de page
$pdf->SetHeaderData('', 0, 'Students List', 'Generated by Schoolara', array(0, 64, 255), array(0, 64, 128));
$pdf->setFooterData(array(0, 64, 0), array(0, 64, 128));

// Définition des marges
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Définir la police par défaut (assurez-vous que la police DejaVu est disponible)
$pdf->SetFont('dejavusans', '', 12, '', true);

// Ajouter une page
$pdf->AddPage();

// Déterminer quel filtre est utilisé
$filter = isset($_GET['filter']) ? $_GET['filter'] : 'all';
$class_id = isset($_GET['class_id']) ? $_GET['class_id'] : '';

// Préparer la requête SQL
$sql = "SELECT students.id, students.name, students.enrollment_date, students.end_date, classes.name as class_name, classes.num_group, students.paid 
        FROM students 
        JOIN classes ON students.class_id = classes.id";
$conditions = [];

// Ajouter des conditions en fonction du filtre
if ($filter === 'class' && !empty($class_id)) {
    $conditions[] = "students.class_id = ?";
} elseif ($filter === 'payment_end_red') {
    $today = date("Y-m-d");
    $conditions[] = "students.end_date <= ?";
}

if (count($conditions) > 0) {
    $sql .= " WHERE " . implode(" AND ", $conditions);
}

// Préparer la requête
$stmt = $conn->prepare($sql);

if ($filter === 'class' && !empty($class_id)) {
    $stmt->bind_param("i", $class_id);
} elseif ($filter === 'payment_end_red') {
    $stmt->bind_param("s", $today);
}

// Exécuter la requête
$stmt->execute();
$result = $stmt->get_result();

// Tableau HTML pour afficher les données
$html = '<h1>Students List</h1>';
$html .= '<table border="1" cellspacing="0" cellpadding="5">
    <thead>
        <tr>
            <th>ID</th>
            <th>Student Name</th>
            <th>Class</th>
            <th>Enrollment Date</th>
            <th>Payment End</th>
            <th>Payment Status</th>
        </tr>
    </thead>
    <tbody>';

while ($row = $result->fetch_assoc()) {
    $html .= '<tr>
        <td>' . $row['id'] . '</td>
        <td>' . $row['name'] . '</td>
        <td>' . $row['class_name'] . ' (' . $row['num_group'] . ')</td>
        <td>' . $row['enrollment_date'] . '</td>
        <td>' . $row['end_date'] . '</td>
        <td>' . ($row['paid'] ? 'Paid' : 'Not Paid') . '</td>
    </tr>';
}

$html .= '</tbody></table>';

// Écrire le contenu HTML dans le PDF
$pdf->writeHTML($html, true, false, true, false, '');

// Nom du fichier PDF à télécharger
$filename = 'students_list_' . date('Y-m-d_H-i-s') . '.pdf';

// Télécharger le fichier PDF généré
$pdf->Output($filename, 'D');

$stmt->close();
$conn->close();
?>
